import './globals.css'
import Headder from '@/components/Headder/Headder'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Headder>Pokedex</Headder>
        {children}
        </body>
    </html>
  )
}
